{
    'name': 'order management',
    'version': '1.0.0',
    'sequence': '-100',
    'author': 'richylife',
    'website': 'www.richylife.ae',
    'category': 'travel',
    'summary': 'order management for travel packages and services',
    'description': 'order management for travel packages and services',
    'depends':[],
    'data':[],
    'installable': True,
    'auto_install': False,
    'application': True,
    'licence': 'LGPL-3',
}